# Generated by Django 3.1.3 on 2021-08-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naSearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Model',
        ),
    ]
